### ISSUE TITLE
Virus reported when installing

### ISSUE THREAD

**Issue by esoffron** [ibrumby/Crossrunner-Issues#2]
Microsoft Defender reported malware when installing.  It could well be a false positive or the legitimate use of a suspicious library (like keyboard sniffing for legit reasons), but... I can't install it like this.

![CleanShot 2023-12-27 at 16 30 54@2x](https://github.com/ibrumby/Crossrunner-Issues/assets/4109731/7d634bc7-1af2-45d5-a2a0-0100ff147663)

**Comment by ibrumby** [comment]
Hi Ernie,

Thanks for the report. I've scanned it with my copy of Microsoft Defender on multiple machines and it was happy with it, but obviously it is not happy about it on your end. I presume you have the latest virus definitions?

Can you try submitting it as a false positive to:
https://www.microsoft.com/en-us/wdsi/filesubmission

Probably better if you submit it since I cannot replicate it.

It is using low level keyboard hooks to emulate the IIGS keyboard.

Cheers,
Ian.

**Comment by ksherlock** [comment]
[this website](https://www.virustotal.com) - can check an uploaded file against 20+ virus engines.  I used it a while back to isolate a false positive.

And ... [it didn't find anything](https://www.virustotal.com/gui/file/0b04807127333c2085c3d658fc3a17a63d8d0e6f2a64981226119e179b6379b2?nocache=1).

**Comment by fadden** [comment]
Another person reported a problem [here](https://groups.google.com/g/comp.emulators.apple2/c/tl0jH_KhA7M).  I'm using Win10 and haven't seen any complaints.  Malwarebytes had no issues with it.

**Comment by ibrumby** [comment]
Thanks for the link @ksherlock. Very useful site.

**Comment by esoffron** [comment]
Submitted.  My Windows VM is managed by my employer, so the definitions are up to date and EXTREMELY twitchy.  I wouldn't be surprised by a false positive, but if nobody says anything then nobody else can fix it if it was real.  You can close this if others think it's a false positive.  (And I'm happy to do Mac testing when you're ready so I can get out having to use Windows!)

**Comment by ibrumby** [comment]
Thanks for submitting.
